//
// Generated by JTB 1.2.2
//

package parser.syntaxtree;

/**
 * Grammar production:
 * f0 -> <DELETE>
 * f1 -> <FROM>
 * f2 -> Table()
 * f3 -> [ Where() ]
 */
public class Delete implements Node {
   private Node parent;
   public NodeToken f0;
   public NodeToken f1;
   public Table f2;
   public NodeOptional f3;

   public Delete(NodeToken n0, NodeToken n1, Table n2, NodeOptional n3) {
      f0 = n0;
      if ( f0 != null ) f0.setParent(this);
      f1 = n1;
      if ( f1 != null ) f1.setParent(this);
      f2 = n2;
      if ( f2 != null ) f2.setParent(this);
      f3 = n3;
      if ( f3 != null ) f3.setParent(this);
   }

   public Delete(Table n0, NodeOptional n1) {
      f0 = new NodeToken("delete");
      if ( f0 != null ) f0.setParent(this);
      f1 = new NodeToken("from");
      if ( f1 != null ) f1.setParent(this);
      f2 = n0;
      if ( f2 != null ) f2.setParent(this);
      f3 = n1;
      if ( f3 != null ) f3.setParent(this);
   }

   public void accept(parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

