//
// Generated by JTB 1.2.2
//

package parser.syntaxtree;

/**
 * Grammar production:
 * f0 -> [ "(" ]
 * f1 -> EqualityExpression()
 * f2 -> ( <OR> EqualityExpression() )*
 * f3 -> [ ")" ]
 */
public class OrExpression implements Node {
   private Node parent;
   public NodeOptional f0;
   public EqualityExpression f1;
   public NodeListOptional f2;
   public NodeOptional f3;

   public OrExpression(NodeOptional n0, EqualityExpression n1, NodeListOptional n2, NodeOptional n3) {
      f0 = n0;
      if ( f0 != null ) f0.setParent(this);
      f1 = n1;
      if ( f1 != null ) f1.setParent(this);
      f2 = n2;
      if ( f2 != null ) f2.setParent(this);
      f3 = n3;
      if ( f3 != null ) f3.setParent(this);
   }

   public void accept(parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

