/* Generated By:JavaCC: Do not edit this line. SimpleSQLParserConstants.java */
package parser.gene;

public interface SimpleSQLParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int SELECT = 13;
  int FROM = 14;
  int WHERE = 15;
  int AND = 16;
  int OR = 17;
  int IN = 18;
  int NOT = 19;
  int AS = 20;
  int CREATE = 21;
  int DROP = 22;
  int TABLE = 23;
  int UPDATE = 24;
  int SET = 25;
  int DELETE = 26;
  int INSERT = 27;
  int VALUES = 28;
  int INTO = 29;
  int VARCHAR = 30;
  int INTEGER = 31;
  int FLOAT = 32;
  int INTEGER_LITERAL = 33;
  int DECIMAL_LITERAL = 34;
  int HEX_LITERAL = 35;
  int OCTAL_LITERAL = 36;
  int FLOATING_POINT_LITERAL = 37;
  int EXPONENT = 38;
  int CHARACTER_LITERAL = 39;
  int STRING_LITERAL = 40;
  int IDENTIFIER = 41;
  int LETTER = 42;
  int DIGIT = 43;
  int LPAREN = 44;
  int RPAREN = 45;
  int COMMA = 46;
  int DOT = 47;
  int EQ = 48;
  int LT = 49;
  int GT = 50;
  int LE = 51;
  int GE = 52;
  int NE = 53;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"select\"",
    "\"from\"",
    "\"where\"",
    "\"and\"",
    "\"or\"",
    "\"in\"",
    "\"not\"",
    "\"as\"",
    "\"create\"",
    "\"drop\"",
    "\"table\"",
    "\"update\"",
    "\"set\"",
    "\"delete\"",
    "\"insert\"",
    "\"values\"",
    "\"into\"",
    "\"varchar\"",
    "\"integer\"",
    "\"float\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
  };

}
